presubmits:
  kubernetes-sigs/kubebuilder-declarative-pattern:
  - name: pull-declarative-test
    decorate: true
    path_alias: sigs.k8s.io/kubebuilder-declarative-pattern
    always_run: true
    spec:
      containers:
      - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20221010-3da4a9c21a-master
        command:
        - "./hack/ci/test.sh"
